screenshot - '-n' flag for notifications

diff --git a/src/screenshot b/src/screenshot
--- a/src/screenshot
+++ b/src/screenshot
@@ -5,24 +5,20 @@ umask 077
 # Directory where screenshots are saved
 screenshots_directory="$HOME"/pictures/screenshots
 
+# Notifications
+notifications=0
+
 # Error messages
 directory_error_message="$screenshots_directory is not properly configured. Halting."
 flag_error_message="Invalid flag. Halting"
 type_error_message="Invalid screenshot type. Halting."
-
-# Check the directory where screenshots exists and has the right permissions
-if ! [ -d "$screenshots_directory" ] || ! [ -r "$screenshots_directory" ] || ! [ -w "$screenshots_directory" ] || ! [ -x "$screenshots_directory" ]; then
-	notify-send "Error" "$directory_error_message"
-	echo "$directory_error_message" 1>&2
-	exit 1
-fi
 
 # Parse optional flags
 opts=''
 curropt=''
 optgroup=''
 virtoptgroup=''
-while getopts "bc" curropt; do
+while getopts "bcn" curropt; do
 	paramgroup="$1"
 	case "$curropt" in
 		b)
@@ -31,8 +27,11 @@ while getopts "bc" curropt; do
 		c)
 			flag="--hidecursor"
 			;;
+		n)
+			notifications=1
+			;;
 		*)
-			notify-send "Error" "$flag_error_message"
+			[ "$notifications" -eq 1 ] && notify-send "Error" "$flag_error_message"
 			echo "$flag_error_message" 1>&2
 			exit 1
 			;;
@@ -46,6 +45,13 @@ while getopts "bc" curropt; do
 		optgroup=''
 	fi
 done
+
+# Check the directory where screenshots will be saved exists and has the right permissions
+if ! [ -d "$screenshots_directory" ] || ! [ -r "$screenshots_directory" ] || ! [ -w "$screenshots_directory" ] || ! [ -x "$screenshots_directory" ]; then
+	[ "$notifications" -eq 1 ] && notify-send "Error" "$directory_error_message"
+	echo "$directory_error_message" 1>&2
+	exit 1
+fi
 
 # Select screenshot type
 case "$1" in
@@ -62,7 +68,7 @@ case "$1" in
 		opts="${opts} --select --bordersize=3 --color=255,255,255"
 		;;
 	*)
-		notify-send "Error" "$type_error_message"
+		[ "$notifications" -eq 1 ] && notify-send "Error" "$type_error_message"
 		echo "$type_error_message" 1>&2
 		exit 0
 		;;
@@ -71,7 +77,7 @@ esac
 # Take the screenshot according to selected options
 screenshot_name=screenshot-"$(date "+%Y-%m-%d-%H-%M-%S")".png
 if maim $opts --delay=0 --format=png --quality 10 "${screenshots_directory}"/"${screenshot_name}"; then
-	notify-send "Screenshot saved" "$screenshot_name"
+	[ "$notifications" -eq 1 ] && notify-send "Screenshot saved" "$screenshot_name"
 	echo "${screenshots_directory}/${screenshot_name}"
 	exit 0
 fi
